# Generated by Django 4.2.4 on 2023-09-09 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0004_alter_teacher_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='photo',
            field=models.ImageField(default='./photos/teachers/photo_placeholder.jpg', upload_to='photos/teachers/'),
        ),
    ]
