# Generated by Django 4.2.4 on 2023-09-23 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordruler', '0003_alter_letter_letter_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='letter_img',
            field=models.ImageField(blank=True, default=1, upload_to='photos/letters/'),
            preserve_default=False,
        ),
    ]
