# Generated by Django 4.2.4 on 2023-10-03 00:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wordruler', '0006_alter_wordruler_letters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='wordruler',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
