# Generated by Django 4.2.4 on 2023-10-03 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordruler', '0007_alter_letter_id_alter_wordruler_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='wordruler',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
