# Generated by Django 4.2.4 on 2023-10-03 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordruler', '0008_alter_letter_id_alter_wordruler_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='dummyf',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
