# Generated by Django 4.2.4 on 2023-10-03 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wordruler', '0009_letter_dummyf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letter',
            name='dummyf',
        ),
    ]
