# Generated by Django 4.2.4 on 2023-09-09 16:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='lesson_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
